[package]
name = "liglicko2-research"
publish = false
edition = "2021"

[dependencies]
chrono = "0.4.38"
compensated-summation = "0.3.0"
csv = "1.3.0"
liglicko2 = { path = ".." }
serde = { version = "1.0.214", features = ["derive"] }
serde_with = "3.11.0"
thiserror = "1.0.65"
